export const SET_APPLICATIONS_DATA = 'SET_APPLICATIONS_DATA';
export const GET_APPLICATIONS_BEGIN = 'GET_APPLICATIONS_BEGIN';
export const GET_APPLICATIONS_FAILURE = 'GET_APPLICATIONS_FAILURE';
export const GET_APPLICATIONS_SUCCESS = 'GET_APPLICATIONS_SUCCESS';
export const SET_CREATE_APPLICATIONS_DATA = 'SET_CREATE_APPLICATIONS_DATA';
export const GET_CREATE_APPLICATIONS_BEGIN = 'GET_CREATE_APPLICATIONS_BEGIN';
export const GET_CREATE_APPLICATIONS_FAILURE = 'GET_CREATE_APPLICATIONS_FAILURE';
export const GET_CREATE_APPLICATIONS_SUCCESS = 'GET_CREATE_APPLICATIONS_SUCCESS';